<?php

declare(strict_types=1);

/** @var \Codilar\GiftBox\Block\Cart\GiftBox $block */
/** @var \Magento\Framework\Escaper $escaper */

$coffeeSkus = $block->getCoffeeSkus();
$equipmentSku = $block->getEquipmentSku();
$giftMessage = $block->getGiftMessage();
?>

<div class="giftbox-cart-details">
    <strong>
        <?= $escaper->escapeHtml(
            __('Gift Box Contents')
        ) ?>
    </strong>
    <?php if ($coffeeSkus): ?>
        <div class="giftbox-cart-section">
            <strong>
                <?= $escaper->escapeHtml(
                    __('Coffees')
                ) ?>
            </strong>
            <ul>
                <?php foreach ($coffeeSkus as $sku): ?>
                    <li>
                        <?= $escaper->escapeHtml(
                            $block->getProductName($sku)
                        ) ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <?php if ($equipmentSku): ?>
        <div class="giftbox-cart-section">
            <strong>
                <?= $escaper->escapeHtml(
                    __('Equipment')
                ) ?>
            </strong>
            <div>
                <?= $escaper->escapeHtml(
                    $block->getProductName($equipmentSku)
                ) ?>
            </div>
        </div>
    <?php endif; ?>


    <?php if ($giftMessage): ?>
        <div class="giftbox-cart-section">
            <strong>
                <?= $escaper->escapeHtml(
                    __('Gift Message')
                ) ?>
            </strong>
            <div>
                <?= $escaper->escapeHtml(
                    $giftMessage
                ) ?>
            </div>
        </div>
    <?php endif; ?>

</div>
